#ifndef __RETURN_CODE_H__
#define __RETURN_CODE_H__

#define SUCCESS 0
#define FAILURE 1
#define INVALID_COMMAND 2
#define DEVICE_NOT_FOUND 3
#define LINK_FAILED 4
#define DEVICE_TYPE_MISMATCH 5
#define CHANGE_PARENT_COMMAND 6
#define CHANGE_CHILD_COMMAND 7
#define DEL_COMMAND 8
#define SWITCH_COMMAND 9
#define INFO_COMMAND 10
#define HUB_FULL 11
#define ALREADY_LINKED 12
#define CONTROL_DEVICE_FULL 13




#endif