#ifndef __RETURN_CODE_H__
#define __RETURN_CODE_H__

#define SUCCESS 0
#define FAILURE 1
#define INVALID_COMMAND 2
#define DEVICE_NOT_FOUND 3
#define LINK_FAILED 4
#define DEVICE_TYPE_MISMATCH 5
#define CHANGE_PARENT_COMMAND 6
#define CHANGE_CHILD_COMMAND 7
#define CHILD_DEL_COMMAND 8
#define SELF_DEL_COMMAND 9
#define SWITCH_COMMAND 10
#define SELF_INFO_COMMAND 11
#define CHILD_INFO_COMMAND 12
#define CHECK_SPACE 13
#define CONTROL_DEVICE_FULL 14
#define CONTROL_DEVICE_INCOMPLETE 15
#define ALREADY_LINKED 16
#define PIPE_ERROR 17
#define TIME_OUT 18




#endif